version: "3.9"
services:
  frontend:
    build: ./apps/frontend
    ports: ["3000:3000"]
    env_file: .env
    depends_on: [backend]
  backend:
    build: ./apps/backend
    ports: ["4000:4000"]
    env_file: .env
    depends_on: [db, quarkid-proxy]
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: lastwish
      POSTGRES_USER: lastwish
      POSTGRES_PASSWORD: secret
  quarkid-proxy:
    image: quarkid/api-proxy:0.7.3
    env_file: .env
